---
- name: Add group "webhook"
  group: name=webhook

- name: Add user "webhook"
  user: 
    name: webhook 
    group: webhook
    groups: ""
    home: /var/webhook
    shell: /bin/false

- name: Install webhook package
  apt:
    pkg: ['webhook']
    update_cache: yes
  when: not ansible_unit_test

- name: Create test directory
  become: yes
  file:
    path: "{{ prefix_dir}}/var/webhook"
    state: directory
    owner: webhook
    group: webhook

  # TODO: put in jinja template
- name: Copy webhook hooks.json file
  become: yes
  template:
    src: templates/hooks.json.j2
    dest: "{{ prefix_dir }}/var/webhook/hooks.json"
    owner: webhook
    group: webhook
    mode: u=rw,g=r,o=r

- name: Install systemd file for webhook
  template: src=templates/webhook.service.j2 dest={{ prefix_dir }}/etc/systemd/system/webhook.service owner=root group=root mode="u=rw,g=r,o=r"
  when: not ansible_unit_test

- name: Enable and start webhook service
  service: name=webhook enabled=true state=restarted
  when: not ansible_unit_test
